### ISSUE TITLE
Cannot shutdown Tomcat 8.5

### ISSUE THREAD

**Issue by rwankar** [redhat-developer/vscode-server-connector#539]
I'm using the latest VSCode (1.67.2) with Community Server Connector (v0.25.4) and Tomcat 8.5.79.

I am able to start the server just fine. When I stop it I get the following messages in the output.

> Configuration error
java.io.FileNotFoundException: ${server.base.dir}/conf/logging.properties (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:499)
	at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:333)
	at java.logging/java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:445)
	at java.logging/java.util.logging.LogManager$2.run(LogManager.java:394)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.logging/java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:382)
	at java.logging/java.util.logging.LogManager.getLogManager(LogManager.java:430)
	at java.logging/java.util.logging.Logger.demandLogger(Logger.java:648)
	at java.logging/java.util.logging.Logger.getLogger(Logger.java:717)
	at java.logging/java.util.logging.Logger.getLogger(Logger.java:701)
	at org.apache.juli.logging.DirectJDKLog.<init>(DirectJDKLog.java:61)
	at org.apache.juli.logging.DirectJDKLog.getInstance(DirectJDKLog.java:181)
	at org.apache.juli.logging.LogFactory.getInstance(LogFactory.java:130)
	at org.apache.juli.logging.LogFactory.getInstance(LogFactory.java:153)
	at org.apache.juli.logging.LogFactory.getLog(LogFactory.java:208)
	at org.apache.catalina.startup.Bootstrap.<clinit>(Bootstrap.java:50)
Jun 02, 2022 9:34:51 AM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/Users/ravi/psa/bin/${server.home.dir}/lib], exists: [false], isDirectory: [false], canRead: [false]
Jun 02, 2022 9:34:51 AM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/Users/ravi/psa/bin/${server.home.dir}/lib], exists: [false], isDirectory: [false], canRead: [false]
java.lang.ClassNotFoundException: org.apache.catalina.startup.Catalina
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.apache.catalina.startup.Bootstrap.init(Bootstrap.java:262)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:445)

The directory path **[/Users/ravi/psa/bin/${server.home.dir}/lib]** is incorrect. Is a ";" is missing before **${server.home.dir}/lib**?

My server config file looks like this..

> {
  "args.override.boolean": "true",
  "args.vm.override.string": "-Djava.util.logging.config.file=/Users/ravi/psa/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Dcatalina.base=/Users/ravi/psa -Dcatalina.home=/Users/ravi/psa -Djava.io.tmpdir=/Users/ravi/psa/temp -Dshutdown.port=8005 -Dajp.port=8009 -Dhttp.port=8888 -Dhttps.port=0 -Dsecuresession=true",
  "id": "main",
  "id-set": "true",
  "org.jboss.tools.rsp.server.typeId": "org.jboss.ide.eclipse.as.server.tomcat.85",
  "server.home.dir": "/Users/ravi/psa",
  "server.http.port": "8888",
  "vm.install.path": "/Library/Java/JavaVirtualMachines/liberica-jdk-11.jdk/Contents/Home"
}

**Comment by robstryker** [comment]
I'm no longer able to replicate this. I think it was a temporary bug when I first separated out the `server.base.dir` flag
